// Generated by scripts/build-ybm.mjs
import type { EtsTest } from '@/types/domain';
export const YBM_LOADERS: Record<string, () => Promise<EtsTest>> = {
  'ybm2025-t1': () => import('./ybm2025-t1.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t2': () => import('./ybm2025-t2.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t3': () => import('./ybm2025-t3.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t4': () => import('./ybm2025-t4.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t5': () => import('./ybm2025-t5.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t6': () => import('./ybm2025-t6.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t7': () => import('./ybm2025-t7.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t8': () => import('./ybm2025-t8.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t9': () => import('./ybm2025-t9.json').then(m => m.default as unknown as EtsTest),
  'ybm2025-t10': () => import('./ybm2025-t10.json').then(m => m.default as unknown as EtsTest),
};
