// Original sentence bank. Each column supplies a different context for one test.
// Correct answer first; the builder rotates options and interleaves grammar topics.
const bank = (answer, distractors, topic, rationale, stems) => ({ answer, distractors, topic, rationale, stems });
export const PART5 = [
 bank('her', ['hers','herself','she'], 'possessive', 'Cần tính từ sở hữu trước danh từ; hers là đại từ sở hữu, herself là phản thân, she là chủ ngữ.', [
 'Ms. Lin submitted ------- expense report before leaving for the trade fair.',
 'The editor credited Ms. Cruz for ------- research into regional tourism.',
 'Dr. Noor has asked the laboratory to forward ------- results to the clinic.',
 'Ms. Ito keeps a printed copy of ------- appointment schedule at reception.',
 'The committee approved Ms. Stone’s proposal after reviewing ------- budget.',
 'Ms. Reed will demonstrate ------- new ordering system to restaurant owners.',
 'For security reasons, Ms. Park must show ------- employee badge at the gate.',
 'Ms. Gray discussed ------- findings with the entire design department.',
 'The host thanked Ms. Bell for ------- contribution to the radio program.',
 'Ms. Voss included a map with ------- invitation to the supplier meeting.'
 ]),
 bank('carefully', ['careful','care','carefulness'], 'word-form', 'Chỗ trống bổ nghĩa cho hành động, cần trạng từ carefully (cẩn thận), không phải tính từ hoặc danh từ.', [
 'Please examine the rental agreement ------- before signing the final page.',
 'A technician ------- packed the fragile lenses in padded containers.',
 'The volunteers ------- separated reusable materials from the damaged stock.',
 'Our accountant ------- checked each entry against the original receipts.',
 'Visitors should ------- follow the route marked on the gallery map.',
 'The chef ------- measured the ingredients for the new dessert.',
 'Warehouse staff ------- inspected the seals on the incoming cartons.',
 'The project leader ------- reviewed the survey before publishing the results.',
 'Applicants are advised to read the eligibility conditions -------.',
 'The installer ------- aligned the panels before tightening the screws.'
 ]),
 bank('available', ['availability','avail','availably'], 'word-form', 'Sau be/remain/become cần tính từ available (có sẵn); availability là danh từ.', [
 'Additional meeting rooms will become ------- once the renovation is finished.',
 'A digital edition of the city guide is ------- to all subscribers.',
 'The afternoon consultation slot is still ------- for new patients.',
 'Replacement filters are ------- at the service counter on the ground floor.',
 'Several positions remain ------- despite last month’s recruitment campaign.',
 'The full catering menu is ------- on our redesigned website.',
 'Complimentary lockers will be ------- during the outdoor equipment sale.',
 'The downloadable charts are ------- in both color and black and white.',
 'Tickets for the preview performance are ------- exclusively online.',
 'An accessible entrance is ------- on the east side of the building.'
 ]),
 bank('information', ['inform','informative','informatively'], 'word-form', 'Cần danh từ information (thông tin); informative là tính từ, inform là động từ.', [
 'The welcome packet contains ------- about nearby parking facilities.',
 'Please send updated ------- about the delivery route to the dispatcher.',
 'The nurse provided ------- on how to prepare for the examination.',
 'All ------- about the warranty can be found in the instruction booklet.',
 'The hiring team requested more ------- about the applicant’s previous role.',
 'Customers can obtain ------- about seasonal ingredients from the staff.',
 'The brochure includes ------- on the origins of the recycled fabrics.',
 'The newsletter offers ------- about changes to data protection rules.',
 'Listeners may request ------- about upcoming interviews by email.',
 'The site manager needs accurate ------- about the equipment dimensions.'
 ]),
 bank('who', ['whose','which','where'], 'relative-clause', 'Đại từ quan hệ who thay cho người và làm chủ ngữ của mệnh đề sau; whose cần danh từ đi kèm.', [
 'Employees ------- cycle to work may use the showers beside the loading bay.',
 'We are seeking an illustrator ------- can create diagrams for travel guides.',
 'Patients ------- require an interpreter should contact reception in advance.',
 'Customers ------- registered their appliances will receive a maintenance reminder.',
 'Candidates ------- have experience with payroll software will be interviewed first.',
 'Suppliers ------- grow produce locally are invited to meet our purchasing team.',
 'Shoppers ------- bring reusable bags will receive a small discount.',
 'Researchers ------- wish to access the archive must submit a written request.',
 'Performers ------- arrive early may rehearse in Studio B.',
 'Contractors ------- attend the safety briefing will be issued temporary passes.'
 ]),
 bank('by', ['until','during','within'], 'deadline', 'By + mốc thời gian = chậm nhất vào thời điểm đó. Until diễn tả hành động kéo dài; during cần khoảng thời gian; within cần độ dài.', [
 'All reservation forms must reach the venue ------- noon on March 18.',
 'The revised proofs should be returned to the publisher ------- 4 P.M. tomorrow.',
 'To secure the appointment, please confirm your attendance ------- Monday morning.',
 'Warranty claims must be submitted ------- September 30 at the latest.',
 'The shortlisted candidates must respond ------- 5 P.M. on June 12.',
 'Orders for the weekend reception must be finalized ------- Thursday noon.',
 'Entries for the design contest must be uploaded ------- midnight on July 9.',
 'Department heads must approve the spending plan ------- the close of business today.',
 'Artists should send their biographies ------- August 21 at the latest.',
 'The completed inspection report is due ------- 10 A.M. on Friday.'
 ]),
 bank('despite', ['although','unless','because'], 'concession', 'Despite + cụm danh từ diễn tả tương phản; although/unless/because cần mệnh đề có chủ ngữ và động từ.', [
 'The cycling event attracted a large crowd ------- the unusually cold weather.',
 'The guidebook sold well ------- its relatively high price.',
 'The clinic remained open ------- the temporary shortage of staff.',
 'The device performed reliably ------- the extreme humidity in the testing room.',
 'Ms. Duarte accepted the position ------- the longer commute.',
 'The kitchen completed every order ------- the unexpected equipment failure.',
 'The store exceeded its sales target ------- reduced opening hours.',
 'The team delivered the prototype on time ------- a difficult technical problem.',
 'The outdoor concert continued ------- the light rain.',
 'The crew finished the repairs ------- limited access to the work area.'
 ]),
 bank('to review', ['reviewing','reviewed','reviews'], 'infinitive', 'Agree + to V: đồng ý làm việc gì. Các dạng V-ing/quá khứ/ngôi ba không theo cấu trúc này.', [
 'The coordinator has agreed ------- the transport plan before the event.',
 'Our editor agreed ------- the translation at no additional charge.',
 'The specialist has agreed ------- the patient’s records tomorrow.',
 'The service manager agreed ------- the disputed repair invoice.',
 'A senior recruiter has agreed ------- the new interview guidelines.',
 'The head chef agreed ------- the proposed supplier contracts.',
 'The store owner has agreed ------- the revised display sketches.',
 'The consultant agreed ------- the software requirements with our team.',
 'The producer has agreed ------- the program script before recording.',
 'The engineer agreed ------- the structural calculations before construction.'
 ]),
 bank('have been', ['has been','was','being'], 'agreement', 'Chủ ngữ số nhiều + have been; since diễn tả khoảng thời gian từ quá khứ đến nay nên dùng hiện tại hoàn thành.', [
 'The bicycle racks ------- inspected regularly since the facility opened.',
 'The manuscripts ------- stored in climate-controlled rooms since January.',
 'The laboratory instruments ------- calibrated weekly since their installation.',
 'The replacement parts ------- kept in sealed packages since they arrived.',
 'The job applications ------- reviewed daily since the announcement was posted.',
 'The kitchen surfaces ------- cleaned twice a day since the new policy began.',
 'The display windows ------- updated every week since the summer campaign started.',
 'The backup files ------- checked automatically since the server upgrade.',
 'The recording booths ------- reserved for trainees since last month.',
 'The safety barriers ------- monitored continuously since work resumed.'
 ]),
 bank('had left', ['will leave','leaving','has left'], 'past-perfect', 'Hành động rời đi xảy ra trước một mốc quá khứ khác, nên dùng had + V3. Các thì tương lai/hiện tại không khớp mạch thời gian.', [
 'By the time the delivery van reached the depot yesterday, the supervisor -------.',
 'When the author arrived at the studio last night, the photographer -------.',
 'Before the clinic received the urgent message yesterday, Dr. Salim -------.',
 'The customer discovered that the installer ------- before the fault appeared.',
 'By the time the recruiter called yesterday afternoon, the applicant -------.',
 'When the supplier reached the restaurant yesterday, the purchasing manager -------.',
 'The courier found that the shop assistant ------- before the parcel arrived.',
 'When the server alarm sounded last night, the technician -------.',
 'By the time the final guest arrived yesterday, the presenter -------.',
 'The foreman learned that the inspector ------- before the crew returned.'
 ]),
 bank('so that', ['as well as','in spite of','rather than'], 'purpose', 'So that + mệnh đề diễn tả mục đích. Các lựa chọn còn lại không nối được mệnh đề chỉ mục đích này.', [
 'The route signs were enlarged ------- riders could read them from a distance.',
 'The index was revised ------- readers could locate topics more easily.',
 'The appointment reminders include a map ------- patients can find the new entrance.',
 'The connectors were color-coded ------- users could assemble the device correctly.',
 'The interview schedule was shared early ------- candidates could arrange transportation.',
 'The menu lists ingredients ------- diners can identify potential allergens.',
 'The labels were moved to eye level ------- shoppers could compare prices.',
 'The help page was rewritten ------- new users could resolve common errors.',
 'The rehearsal was recorded ------- performers could evaluate their timing.',
 'Temporary walkways were installed ------- pedestrians could avoid the work zone.'
 ]),
 bank('neither', ['each','any','every'], 'determiner', 'Neither of + hai đối tượng = không đối tượng nào trong hai. Each mang nghĩa mỗi; any/every không diễn đạt việc cả hai đều không phù hợp.', [
 'Both proposed routes were rejected because ------- of them met the required safety standard.',
 'The publisher rejected both cover designs because ------- of them matched the book’s theme.',
 'The patient declined both appointment times because ------- of them suited her schedule.',
 'Both adapters had to be returned because ------- of them fitted the socket.',
 'Both finalists were disqualified because ------- of them had the required license.',
 'The chef decided against both sauces because ------- of them complemented the dish.',
 'We ruled out both suppliers because ------- of them could deliver on Saturday.',
 'The team discarded both recovery tools because ------- of them restored the missing files.',
 'Both venues were removed from consideration because ------- of them could seat 500 guests.',
 'Both proposed repair methods were rejected because ------- of them addressed the underlying damage.'
 ]),
 bank('fewer', ['less','much','little'], 'countable', 'Fewer + danh từ đếm được số nhiều. Less/much/little dùng với danh từ không đếm được.', [
 'The new booking system produces ------- duplicate reservations than the old one.',
 'The revised printing process uses ------- sheets of paper per book.',
 'The reminder service has resulted in ------- missed appointments.',
 'The updated model requires ------- replacement components.',
 'This year, the agency received ------- incomplete applications.',
 'Reusable trays mean that the kitchen needs ------- disposable containers.',
 'Online receipts allow the store to print ------- paper copies.',
 'The new security filter permits ------- suspicious messages to enter the network.',
 'The shorter program includes ------- commercial breaks.',
 'Prefabricated panels require ------- on-site adjustments.'
 ]),
 bank('more convenient', ['most convenient','convenience','conveniently'], 'comparison', 'Than chỉ phép so sánh hơn; convenient là tính từ dài nên dùng more convenient.', [
 'For many commuters, storing a bicycle here is ------- than taking it upstairs.',
 'The searchable digital guide is ------- than the printed directory.',
 'An evening consultation is ------- than a midday visit for working patients.',
 'Ordering spare parts online is ------- than traveling to the warehouse.',
 'A video interview is ------- than a trip to the regional office.',
 'Collecting all the dishes at one counter is ------- than visiting several stalls.',
 'The new parcel lockers are ------- than the former pickup desk.',
 'A single sign-in page is ------- than several separate account portals.',
 'The shuttle service is ------- than finding parking near the theater.',
 'A folding inspection ladder is ------- than a fixed platform for this task.'
 ]),
 bank('responsible', ['responsibility','responsibly','respond'], 'collocation', 'Be responsible for + N/V-ing = chịu trách nhiệm. Cần tính từ responsible.', [
 'The event coordinator is ------- for assigning volunteers to each checkpoint.',
 'The copy editor is ------- for checking references in the final manuscript.',
 'The head nurse is ------- for ordering clinical supplies.',
 'The shift supervisor is ------- for maintaining the repair log.',
 'The recruitment officer is ------- for contacting shortlisted applicants.',
 'The catering manager is ------- for confirming the number of guests.',
 'The branch manager is ------- for approving product returns.',
 'The network administrator is ------- for monitoring backup failures.',
 'The stage manager is ------- for preparing the rehearsal timetable.',
 'The site engineer is ------- for inspecting temporary structures.'
 ]),
 bank('promptly', ['prompt','promptness','prompting'], 'word-form', 'Cần trạng từ promptly (nhanh chóng) bổ nghĩa cho hành động phản hồi/xử lý.', [
 'Damaged rental equipment should be reported ------- to the desk attendant.',
 'The publisher responded ------- to the author’s request for a correction.',
 'Reception staff ------- forwarded the urgent message to the doctor.',
 'The supplier ------- replaced the defective control panel.',
 'The hiring office ------- acknowledged every completed application.',
 'Our team will ------- notify guests of any changes to the menu.',
 'Refund requests are processed ------- once the receipt has been verified.',
 'The support desk ------- restored access to the shared folder.',
 'The ticket office ------- contacted customers about the canceled performance.',
 'Workers must ------- report any damage to the safety fence.'
 ]),
 bank('because of', ['even though','unless','so that'], 'cause', 'Because of + cụm danh từ nêu nguyên nhân. Các liên từ khác cần một mệnh đề.', [
 'The race route was shortened ------- the road closure near the river.',
 'The release date changed ------- a delay at the printing plant.',
 'Several consultations were moved online ------- the building repairs.',
 'The warranty was extended ------- a manufacturing defect in the original model.',
 'The agency added interview sessions ------- the large number of applicants.',
 'The reception will be held indoors ------- the forecast of strong winds.',
 'The store closed early ------- an interruption to the water supply.',
 'The software launch was postponed ------- an unresolved security issue.',
 'The festival schedule was revised ------- a change in the headline performer’s plans.',
 'The inspection was rescheduled ------- restricted access to the site.'
 ]),
 bank('rather than', ['as soon as','even if','so that'], 'contrast', 'Rather than nối hai lựa chọn cùng cấu trúc và mang nghĩa thay vì; các đáp án khác không nối hai động từ nguyên mẫu như ở đây.', [
 'Members may renew their passes online ------- visit the service office.',
 'Authors can upload corrections directly ------- mail printed pages.',
 'Patients can confirm an appointment by text ------- call reception.',
 'Technicians should replace the seal ------- repair it with adhesive.',
 'Applicants should submit one combined file ------- send several attachments.',
 'Guests may choose a vegetarian main course ------- order the standard meal.',
 'Customers can collect their orders at a locker ------- wait for home delivery.',
 'Users should reset their passwords ------- create duplicate accounts.',
 'Visitors may take the shuttle ------- drive to the main gate.',
 'The crew will rent a mobile platform ------- install permanent scaffolding.'
 ]),
 bank('whichever', ['wherever','however','whenever'], 'relative-choice', 'Whichever + danh từ chỉ bất kỳ lựa chọn nào trong số các lựa chọn; các từ khác chỉ nơi chốn/cách thức/thời gian.', [
 'Participants may choose ------- route best suits their level of experience.',
 'The author may select ------- cover design conveys the story most effectively.',
 'Patients can book ------- appointment slot is still open.',
 'The technician may use ------- tool provides the safest grip.',
 'Applicants should contact ------- office is closest to their home.',
 'Guests may order ------- dessert they prefer from the seasonal menu.',
 'Shoppers may visit ------- branch carries their size.',
 'The team can use ------- platform meets the project’s security requirements.',
 'Audience members can attend ------- performance fits their schedule.',
 'The supervisor may approve ------- repair method requires less downtime.'
 ]),
 bank('qualified', ['qualification','qualify','qualifies'], 'word-form', 'Cần tính từ qualified (đủ năng lực) trước danh từ chỉ người; các dạng khác là danh từ hoặc động từ.', [
 'Only ------- mechanics may service the electric bicycles.',
 'The journal relies on ------- reviewers to assess technical submissions.',
 'The clinic is recruiting ------- assistants for its rehabilitation department.',
 'All repairs must be carried out by ------- electricians.',
 'The company has received applications from several ------- accountants.',
 'We are looking for ------- chefs with experience in large events.',
 'A ------- optician will be available in the store next month.',
 'The course is taught by ------- analysts with industry experience.',
 'The orchestra welcomes applications from ------- instructors.',
 'A ------- inspector must approve the structure before it opens.'
 ]),
 bank('ensure', ['restore','assume','consume'], 'vocabulary', 'Ensure = bảo đảm một kết quả. Restore = khôi phục; assume = giả định; consume = tiêu thụ.', [
 'Clear signs help ------- that first-time visitors locate the rental desk.',
 'A final proof check will ------- that no page numbers are missing.',
 'The second identity check will ------- that records are sent to the correct patient.',
 'Routine testing helps ------- that every device meets the safety standard.',
 'The checklist will ------- that all required documents are included.',
 'Temperature monitoring helps ------- that food stays fresh during transport.',
 'A barcode scan will ------- that customers receive the correct item.',
 'Automatic backups help ------- that files can be recovered after an outage.',
 'The sound check will ------- that announcements are audible throughout the hall.',
 'A second inspection will ------- that the repaired barrier is secure.'
 ]),
 bank('comply', ['reply','supply','apply'], 'collocation', 'Comply with = tuân thủ. Reply thường đi với to; apply với for/to; supply không mang nghĩa tuân thủ.', [
 'All cyclists must ------- with the event’s helmet requirement.',
 'Submitted manuscripts must ------- with the journal’s formatting guidelines.',
 'Clinic visitors must ------- with the posted hygiene rules.',
 'Every replacement component must ------- with the national safety standard.',
 'Recruitment agencies must ------- with the company’s privacy policy.',
 'Catering suppliers are required to ------- with food storage regulations.',
 'Online retailers must ------- with the revised refund rules.',
 'All data transfers must ------- with our security procedures.',
 'Event organizers must ------- with the venue’s noise restrictions.',
 'Contractors must ------- with the site’s protective equipment requirements.'
 ]),
 bank('assess', ['access','attach','assign'], 'vocabulary', 'Assess = đánh giá. Access = truy cập; attach = gắn/đính kèm; assign = phân công.', [
 'A short trial ride allows the mechanic to ------- the condition of the brakes.',
 'The editor will ------- the suitability of the proposal for the new series.',
 'The specialist will ------- the patient’s progress at the next visit.',
 'The inspector must ------- the extent of the damage before quoting a price.',
 'The interview panel will ------- each candidate’s problem-solving skills.',
 'The chef will ------- the freshness of the ingredients on arrival.',
 'The buyer will ------- the quality of the samples before placing an order.',
 'The audit team will ------- the effectiveness of the backup procedure.',
 'The producer will ------- the performers’ readiness during rehearsal.',
 'The engineer will ------- the stability of the temporary platform.'
 ]),
 bank('extended', ['extensive','extension','extending'], 'passive', 'Has been + V3 diễn tả bị động: extended (được gia hạn). Extensive là tính từ rộng lớn; extension là danh từ.', [
 'The bicycle return deadline has been ------- by one day.',
 'The manuscript submission period has been ------- until March 28.',
 'The clinic’s opening hours have been ------- for the winter season.',
 'The warranty has been ------- by an additional six months.',
 'The application window has been ------- to attract more candidates.',
 'The catering agreement has been ------- for another year.',
 'The promotional offer has been ------- through the weekend.',
 'The software trial period has been ------- by two weeks.',
 'The exhibition’s run has been ------- until the end of August.',
 'The road closure permit has been ------- for three more days.'
 ]),
 bank('substantial', ['substantially','substance','substantiate'], 'word-form', 'Trước danh từ cần tính từ substantial = đáng kể; substantially là trạng từ, substance là danh từ.', [
 'The new transport partnership produced a ------- reduction in delivery costs.',
 'The digital subscription generated a ------- increase in readership.',
 'The appointment system led to a ------- decrease in waiting times.',
 'The redesigned motor offers a ------- improvement in energy efficiency.',
 'The training program represents a ------- investment in employee development.',
 'The kitchen renovation resulted in a ------- increase in capacity.',
 'The branch expansion requires a ------- amount of additional funding.',
 'The security upgrade delivered a ------- improvement in reliability.',
 'The publicity campaign brought a ------- rise in advance bookings.',
 'The new maintenance schedule produced a ------- reduction in downtime.'
 ]),
 bank('accommodate', ['accumulate','accompany','accomplish'], 'vocabulary', 'Accommodate = đáp ứng nhu cầu/chứa được. Accumulate = tích lũy; accompany = đi cùng; accomplish = hoàn thành.', [
 'The larger storage area can ------- twenty more bicycles.',
 'The publisher adjusted the layout to ------- the additional illustrations.',
 'The waiting room was enlarged to ------- more visitors.',
 'The service desk added evening hours to ------- customers who work during the day.',
 'The recruiter arranged weekend interviews to ------- candidates from other cities.',
 'The restaurant can ------- groups of up to forty people.',
 'The shelving was redesigned to ------- the taller product packages.',
 'The server was upgraded to ------- the growing number of users.',
 'The festival will add an extra screening to ------- public demand.',
 'The access road was widened to ------- larger delivery vehicles.'
 ]),
 bank('eligible', ['legible','edible','flexible'], 'vocabulary', 'Eligible for = đủ điều kiện hưởng/nhận. Legible = dễ đọc; edible = ăn được; flexible = linh hoạt.', [
 'Annual pass holders are ------- for a discount on bicycle repairs.',
 'Student subscribers are ------- for free access to the archive.',
 'Patients referred by a specialist are ------- for the screening program.',
 'Products purchased within the last month are ------- for a replacement.',
 'Employees with two years of service are ------- for the training grant.',
 'Bookings for more than thirty guests are ------- for complimentary delivery.',
 'Members are ------- for early access to the clearance sale.',
 'Nonprofit organizations are ------- for reduced software license fees.',
 'Local schools are ------- for discounted matinee tickets.',
 'Buildings completed before 1990 are ------- for the renovation subsidy.'
 ]),
 bank('inquiries', ['inquirers','inquiring','inquired'], 'word-form', 'Cần danh từ số nhiều inquiries = các câu hỏi/yêu cầu thông tin. Inquirers là người hỏi; các dạng còn lại là động từ.', [
 'Please direct all ------- about bicycle availability to the rental desk.',
 'The publisher received numerous ------- about the forthcoming atlas.',
 'Reception handles ------- about appointment fees and insurance coverage.',
 'Our support team answers ------- about compatible replacement parts.',
 'The careers office responds to ------- about internship opportunities.',
 'The catering department welcomes ------- about dietary requirements.',
 'The store has received several ------- about international shipping.',
 'The training team will handle ------- about course prerequisites.',
 'The festival office accepts ------- about accessibility arrangements.',
 'The planning department reviews ------- about construction permits.'
 ]),
 bank('in addition to', ['in order that','as soon as','even though'], 'addition', 'In addition to + N/V-ing bổ sung thông tin: ngoài … ra còn … . Các đáp án khác cần mệnh đề.', [
 '------- renting bicycles, the center provides guided rides.',
 '------- publishing books, the studio produces educational podcasts.',
 '------- offering consultations, the clinic runs community workshops.',
 '------- repairing appliances, the company sells refurbished models.',
 '------- recruiting permanent staff, the agency arranges temporary placements.',
 '------- preparing meals, the catering team supplies tableware.',
 '------- selling clothing, the shop provides an alteration service.',
 '------- developing software, the firm conducts security audits.',
 '------- hosting concerts, the hall offers rehearsal space.',
 '------- inspecting roofs, the contractor installs insulation.'
 ]),
 bank('unless', ['despite','during','otherwise'], 'condition', 'Unless + mệnh đề = trừ khi/nếu không. Despite/during cần danh từ; otherwise không nối trực tiếp hai mệnh đề theo cấu trúc này.', [
 'A rental deposit will not be refunded ------- the bicycle is returned undamaged.',
 'The manuscript cannot enter production ------- the author approves the final proof.',
 'The clinic will not release the records ------- the patient provides written consent.',
 'The technician cannot replace the component ------- the power is disconnected.',
 'An application will not be considered ------- all required fields are completed.',
 'The kitchen cannot confirm the booking ------- a deposit is received.',
 'A return will not be accepted ------- the original receipt is provided.',
 'The system will not grant access ------- the identity check is completed.',
 'The performance cannot begin ------- the emergency exits are clear.',
 'The crew will not enter the site ------- the safety officer authorizes access.'
 ]),
];
