import {TRACKS} from './scenarios.mjs';
const doc=(heading,content,table)=>({heading,content,...(table?{table}:{})});
const para=(...xs)=>xs.join('\n\n');
const pair=(source,target,meaning)=>({source,target,meaning});
const q=(stem,answer,distractors,evidence,skill='detail',paraphrases=[])=>({stem,answer,distractors,explanation:`${evidence} Đáp án cần bám vào thông tin được nêu trong tài liệu; các lựa chọn khác thay đổi chi tiết hoặc đưa ra thông tin không có căn cứ.`,skill,paraphrases});
export function part6(i){
 const t=TRACKS[i],month=['January','February','March','April','May','June','July','August','September','October'][i];
 const adjective=['accurate','consistent','efficient','reliable','practical','flexible','effective','systematic','thorough','accessible'][i];
 const noun=['assessment','evaluation','review','analysis','study','examination','appraisal','investigation','inspection','audit'][i];
 return [
 {kind:'staff memo',documents:[doc(`${t.org}: stock control`,para(
 `To: All department heads\nFrom: ${t.person}\nSubject: Tracking shared supplies`,
 `Beginning ${month} 3, our office will use a new log for the ${t.item} kept in the central cupboard. Each department must record the quantity it takes and the date of collection. This will help us maintain ------- (131) records without asking staff to count the entire stock every evening.`,
 `Please enter the information ------- (132) you remove any supplies. Entries made much later are difficult to match with delivery records. The log is on the staff portal, next to the weekly duty schedule. ------- (133). Staff who cannot access the portal should contact the reception desk rather than create a separate paper record.`,
 `At the end of each week, the ${t.job} will compare the log with the remaining stock. Your ------- (134) will help us avoid ordering items that are already available. No changes are being made to the procedure for returning damaged supplies.`))],questions:[
 q('',adjective,['accuracy','consistently','efficiency'],`Vị trí “… records” cần tính từ ${adjective} bổ nghĩa cho records. Các lựa chọn còn lại là danh từ/trạng từ.`, 'word-form'),
 q('','before',['during','despite','within'],'Before đứng trước mệnh đề you remove… để chỉ việc ghi nhận phải diễn ra trước khi lấy hàng; các giới từ còn lại không nối trực tiếp mệnh đề.','conjunction'),
 q('','A short demonstration video is available on the same page.',['The portal was permanently removed last year.','Customers must pay for every item online.','The cupboard will be sold to a supplier tomorrow.'],'Same page nối với trang portal vừa nhắc; video hướng dẫn phù hợp với cách dùng log. Không có thay đổi về việc bán tủ hay thanh toán.','sentence-completion'),
 q('','cooperation',['cooperate','cooperatively','cooperated'],'Your cần danh từ cooperation làm chủ ngữ cho will help: sự hợp tác giúp tránh đặt thừa vật dụng. Các dạng động từ/trạng từ không làm chủ ngữ sau your.','word-form')
 ]},
 {kind:'return policy',documents:[doc(`${t.org}: exchange procedure`,para(
 `Customers purchasing ${t.item} from our reception counter may request an exchange within fourteen days. To qualify, the item must be unused and returned with the original receipt. Items showing signs of use cannot be exchanged ------- (135) they were sold with a manufacturing defect.`,
 `Our staff will inspect the returned item and explain the available options. ------- (136). If the same model is out of stock, a credit voucher can be issued instead. The voucher is valid for six months and can be used only at our own counter.`,
 `We cannot ------- (137) the cost of travel to our premises, even when an exchange is approved. Customers who live outside ${t.city} should contact us before sending a parcel. We will provide a reference number so that the package can be routed to the correct desk.`,
 `This policy applies ------- (138) to purchases made directly from ${t.org}. Products obtained from other retailers must be returned to the original seller, whose terms may differ.`))],questions:[
 q('','unless',['because','although','while'],'Unless diễn tả ngoại lệ: hàng đã dùng không đổi được trừ khi có lỗi sản xuất. Because/although/while không thể hiện điều kiện ngoại lệ theo chính sách.','condition'),
 q('','An identical replacement is normally offered first.',['All replacement models have been discontinued forever.','Travel costs are always added to the refund.','Receipts are unnecessary for every exchange.'],'Câu tiếp nói nếu cùng model hết hàng thì dùng voucher; vì vậy việc ưu tiên đổi sản phẩm giống hệt phải xuất hiện trước điều kiện này.','sentence-completion',[pair('identical replacement','the same model','sản phẩm thay thế cùng mẫu')]),
 q('','reimburse',['reimbursement','reimbursable','reimbursed'],'Sau cannot cần nguyên mẫu reimburse = hoàn lại chi phí. Chính sách nói không hoàn tiền đi lại; danh từ/tính từ/phân từ không theo động từ khuyết thiếu.','vocabulary'),
 q('','exclusively',['exclusive','exclusivity','exclude'],'Exclusively là trạng từ bổ nghĩa cho applies = chỉ áp dụng. Exclusive/exclusivity/exclude có từ loại không phù hợp trong câu này.','word-form')
 ]},
 {kind:'e-mail',documents:[doc('Revised visit arrangements',para(
 `To: ${t.person}\nFrom: Ellis Grant, Program Office\nDate: ${month} 8\nSubject: Visit to ${t.venue}`,
 `Thank you for confirming the names of the participants in our ${t.topic} visit. We originally planned to start at 9 A.M., but the first demonstration has been moved to 10 A.M. because the presenter will be arriving from another city. We have ------- (139) the room booking accordingly.`,
 `------- (140). You are welcome to leave coats and bags there before joining the group. The demonstration itself will take place in the upstairs classroom, and an elevator is available for anyone who needs it.`,
 `Please ask participants ------- (141) their visitor passes on arrival. A staff member will check the names against the list you supplied. People whose names are not on the list should wait at the desk while we confirm their registration.`,
 `There will be no extra charge for the later start. ------- (142), the afternoon session will finish at the originally advertised time. We have shortened the lunch break to keep the overall schedule on track.`))],questions:[
 q('','adjusted',['adjustment','adjusting','adjustable'],'Have cần phân từ quá khứ adjusted trong hiện tại hoàn thành, diễn tả đã sửa đặt phòng theo giờ mới. Các lựa chọn khác không tạo thì này.','tense'),
 q('','The reception desk will still open at its usual time.',['The classroom has been closed permanently.','Lunch will be served in another country.','All visitor passes have already been destroyed.'],'There ở câu sau chỉ reception desk vừa được giới thiệu, nơi có thể gửi đồ trước giờ học. Câu chọn giữ mạch chuẩn bị dù bắt đầu muộn.','sentence-completion'),
 q('','to collect',['collecting','collection','collected'],'Ask somebody to do something: yêu cầu người tham gia nhận thẻ. To collect đúng cấu trúc; ba lựa chọn còn lại không là nguyên mẫu có to.','infinitive'),
 q('','Nevertheless',['As a result','For instance','Similarly'],'Bắt đầu muộn nhưng kết thúc như cũ là ý tương phản nên dùng Nevertheless. As a result chỉ kết quả, For instance nêu ví dụ, Similarly nêu tương đồng.','transition')
 ]},
 {kind:'newsletter article',documents:[doc(`${t.org}: lessons from the trial`,para(
 `A six-week trial of the new ${t.topic} service concluded on ${month} 14. During the trial, volunteers recorded the time needed to complete each task and wrote comments about unclear instructions. Their reports formed the basis of a detailed ------- (143) carried out by our planning team.`,
 `The findings show that participants completed the tasks more quickly after the instructions were rewritten. The greatest improvement occurred among people ------- (144) had never used the service before. Experienced users also benefited, although the difference was smaller.`,
 `------- (145). The final version will use larger labels and separate instructions for the first visit and later visits. We will also add an illustrated guide at the reception counter.`,
 `The team expects these changes to reduce requests for assistance. However, staff will continue to be available throughout opening hours. Anyone interested in joining the next trial should contact ${t.person} ------- (146) ${month} 25, the closing date for applications.`))],questions:[
 q('',noun,['evaluate','analytically','reviewed'],`Sau “a detailed” cần danh từ ${noun} = hoạt động đánh giá. Các lựa chọn còn lại là động từ, trạng từ hoặc phân từ không tạo cụm này.`, 'word-form'),
 q('','who',['whose','where','which'],'People chỉ người; who làm chủ ngữ had never used. Whose cần danh từ phía sau, where chỉ nơi và which không phù hợp khi thay người ở đây.','relative-clause'),
 q('','These observations have guided several design decisions.',['No volunteers submitted any comments during the trial.','The trial will begin for the first time next year.','The planning team has decided to remove all instructions.'],'These observations thay cho findings vừa nêu, dẫn tới những thay đổi thiết kế ở câu tiếp. Các phương án khác phủ nhận dữ kiện hoặc đảo sai thời gian.','sentence-completion',[pair('findings','observations','kết quả/điều quan sát được trong thử nghiệm')]),
 q('','by',['until','during','since'],`By ${month} 25 là hạn chót nộp đơn, được xác nhận bởi closing date. Until diễn tả kéo dài tới mốc; during/since không phù hợp với hạn hoàn thành.`, 'deadline')
 ]}
 ];
}
export function part7(i){
 const t=TRACKS[i], month=['January','February','March','April','May','June','July','August','September','October'][i],date=10+i,fee=t.base,unit=12+i,quantity=8+i;
 const groups=[];const add=(kind,documents,questions)=>groups.push({kind,documents,questions});
 add('notice',[doc(`${t.venue}: access arrangements`,para(
 `From ${month} ${date} through ${month} ${date+3}, the main entrance to ${t.venue} will be unavailable while a damaged handrail is replaced. Visitors should use the courtyard entrance beside the bicycle racks. The building's opening hours and all scheduled activities will remain the same.`,
 `A member of the ${t.org} reception team will be stationed in the courtyard to give directions. Wheelchair users may request assistance at the call button next to the side door. Delivery drivers should continue to use the loading gate, which is unaffected by the repair work.`,
 `Please allow a few extra minutes to reach your room. No appointment changes are necessary. Once the repair has been inspected, notices will be removed and the main entrance will reopen.`))],[
 q('Why was the notice issued?','To explain a temporary entrance change',['To announce longer opening hours','To cancel all scheduled appointments','To advertise bicycle repairs'],'Handrail đang được thay nên cửa chính tạm đóng, khách dùng cửa courtyard. Thông báo giữ nguyên giờ mở cửa và các hoạt động.','purpose'),
 q('Who should continue to use the loading gate?','Delivery drivers',['All visitors','Wheelchair users only','The inspection committee'],'Văn bản trực tiếp nói delivery drivers tiếp tục dùng loading gate; khách tham dự được hướng dẫn đến cửa courtyard.','detail')
 ]);
 add('e-mail',[doc('A revised supply request',para(
 `To: Sales Office\nFrom: ${t.person}, ${t.org}\nSubject: Order revision`,
 `I submitted a request for ${quantity} sets of ${t.item} yesterday. After checking our storage room, I found two unopened sets from an earlier purchase. Please reduce the new order by two sets and send a revised confirmation showing the new amount. We still require delivery before the end of this month.`,
 `The billing address is correct, but the parcel should go to ${t.venue} rather than our administrative office. The receiving desk there is staffed from 8 A.M. to 4 P.M. Please put my name on the delivery label so the staff can contact me when it arrives.`,
 `I appreciate your help. If the order has already left your warehouse, call me before making any changes. I will arrange to keep the extra sets for our next program.`))],[
 q('Why does the sender want to reduce the order?','Some supplies are already available',['The program has been canceled','The supplier raised its prices','The venue cannot accept deliveries'],'Người gửi tìm thấy hai bộ chưa mở trong kho, nên giảm đơn hai bộ; chương trình và thời hạn giao vẫn giữ nguyên.','reason',[pair('two unopened sets from an earlier purchase','supplies already available','vật dụng còn sẵn từ lần mua trước')]),
 q('What should the seller do if the goods have already been dispatched?','Call the sender',['Deliver them to the administrative office','Discard the delivery label','Cancel the order without notice'],'Câu cuối yêu cầu call me trước khi sửa đơn nếu hàng đã rời kho; người gửi sẽ giữ phần dư cho chương trình tiếp theo.','condition')
 ]);
 add('advertisement',[doc(`${t.event}: practical sessions`,para(
 `${t.org} invites local residents to a one-day introduction to ${t.topic} at ${t.venue} on ${month} ${date+4}. The morning session will demonstrate basic techniques, while the afternoon session will allow participants to try them in small groups. No previous experience is required.`,
 `The fee of $${fee} covers both sessions and the use of all practice materials. Participants should bring their own lunch; drinking water will be provided. Registration closes five days before the event or earlier if all thirty places are filled. Payment must be received before a place is confirmed.`,
 `A certificate of participation can be requested at the end of the day. It is intended as a record of attendance and does not serve as a professional qualification. Contact ${t.person} for accessibility arrangements or questions about the program.`))],[
 q('Who is the program suitable for?','People without prior experience',['Only certified specialists','Children traveling without adults','Employees of one supplier only'],'No previous experience is required cho phép người mới học đăng ký, không giới hạn ở chuyên gia có chứng chỉ.','audience'),
 q('What is included in the fee?','Practice materials',['A professional license','Lunch from a restaurant','An overnight stay'],'Fee covers sessions và use of all practice materials. Bài yêu cầu tự mang lunch, chứng nhận không là bằng nghề.','detail'),
 q('When is a registration confirmed?','After payment is received',['When the event ends','When a certificate is requested','After an overnight booking'],'Payment must be received before a place is confirmed nêu điều kiện xác nhận. Điền tên mà chưa trả phí chưa đủ.','sequence')
 ]);
 const synonyms=[['maintain','keep'],['anticipates','expects'],['sole','only'],['outstanding','excellent'],['complimentary','free'],['exceeded','surpassed'],['handle','manage'],['promote','encourage'],['facility','building'],['coverage','reporting']];const [word,target]=synonyms[i];
 const context=[
 'The organizers aim to maintain the same service standards as attendance increases.',
 'The committee anticipates further growth after the introductory sessions begin.',
 'The organization is the sole provider of this program in the district.',
 'Participants praised the outstanding support offered by the volunteer team.',
 'Visitors received complimentary printed guides at the opening session.',
 'The number of registrations exceeded the initial target by forty places.',
 'Two additional coordinators will handle requests during the busiest period.',
 'The scheme is intended to promote cooperation among neighborhood groups.',
 'The facility contains two classrooms and a reception area on the ground floor.',
 'A regional newspaper provided coverage of the opening ceremony.'
 ][i];
 add('article',[doc(`${t.city} Gazette — a shared initiative`,para(
 `${t.org} has completed the first stage of a neighborhood initiative focused on ${t.topic}. The project began when local groups asked for a place where they could learn practical skills without buying equipment for individual use. A former office near ${t.venue} was adapted for this purpose.`,
 context+' The project is funded jointly by the town council and several local associations. Neither group expects participants to purchase annual memberships.',
 `According to ${t.person}, the next priority is to extend evening access. Daytime visitors have responded positively, but some residents work until late afternoon and cannot attend current sessions. Before introducing new hours, the team will survey residents about the days they prefer. The survey results will be published on the organization's website.`))],[
 q('Why was the initiative established?','To provide shared learning resources',['To sell annual memberships','To replace the town council','To close a former classroom'],'Mục đích xuất phát từ nhu cầu học kỹ năng mà không mua thiết bị riêng. Bài nhấn mạnh không yêu cầu mua annual memberships.','purpose'),
 q(`The word “${word}” is closest in meaning to`,target,['postpone','calculate','remove'].filter(x=>x!==target),`Trong câu “${context}”, ${word} tương đương ${target}; phải xét nghĩa tại câu này thay vì một nghĩa khác của từ.`, 'synonym',[pair(word,target,'nghĩa tương đương trong ngữ cảnh của bài báo')]),
 q('What will the organization do before extending its hours?','Survey residents',['Purchase annual memberships','Demolish the office','Cancel all daytime sessions'],'Trước introducing new hours, team sẽ hỏi residents về những ngày họ muốn tham gia. Đây là bước thu thập nhu cầu trước khi đổi giờ.','sequence')
 ]);
 add('text-message chain',[doc('Operations team chat',para(
 `8:40 A.M. — ${t.person}: The ${t.item} for this morning's demonstration are still at the office. Can someone collect them on the way to ${t.venue}?\n8:42 A.M. — Dana: I'm leaving the office in ten minutes. I'll bring them with me.\n8:43 A.M. — ${t.person}: Thanks. Please check that the instruction sheets are inside each set. We ran short of them last time.\n8:44 A.M. — Dana: I'll make sure we have enough. Where should I leave everything?\n8:45 A.M. — ${t.person}: On the table beside reception. The upstairs classroom is being cleaned until 9:30.\n8:46 A.M. — Dana: That works for me. I'll be there before nine.\n8:47 A.M. — ${t.person}: Great. I'll ask the receptionist to watch the table until we move the materials upstairs.`))],[
 q('What does Dana offer to do?',`Transport the ${t.item}`,['Clean the upstairs classroom','Print a new registration form','Cancel the demonstration'],'Dana nói sẽ bring them khi rời office; them chỉ các vật dụng cần cho buổi demonstration, không phải dọn phòng.','detail'),
 q('At 8:46 A.M., what does Dana mean by “That works for me”?','The proposed arrangement is acceptable',['The materials are defective','The classroom has opened early','A new job has been offered'],'Dana chấp thuận để đồ cạnh reception và đến trước chín giờ. Works for me diễn tả phương án phù hợp, không phải máy móc hoạt động.','intent',[pair('That works for me','The arrangement is acceptable','phương án đó phù hợp với tôi')]),
 q('What problem occurred at a previous demonstration?','There were too few instruction sheets',['The receptionist canceled the event','The office closed at eight','All materials were damaged'],'Ran short of them liên hệ trực tiếp instruction sheets câu trước: từng thiếu tờ hướng dẫn. Không nói thiếu bộ vật dụng hay hỏng thiết bị.','inference',[pair('ran short of','had too few','không có đủ')])
 ]);
 add('schedule',[doc(`${t.event}: volunteer briefing`,para(
 `Venue: ${t.venue}\nDate: ${month} ${date+4}`,
 `All new volunteers must attend the introductory briefing. Afterward, they should attend the workshop assigned to their role. Both role-specific workshops start at 10 A.M., so volunteers cannot attend both. Returning volunteers may skip the introduction but should check the revised procedure in their own workshop.`,
 `The lunch break is shared by both groups. The final question period will be held in the auditorium, allowing all volunteers to discuss problems with the organizing committee. Bring your confirmation email to reception on arrival. Room assignments are fixed; requests to switch groups must be approved by ${t.person} before the briefing day.`),{headers:['Time','Session','Location'],rows:[['9:00–9:45','Introduction','Auditorium'],['10:00–11:15','Reception team','Room A'],['10:00–11:15','Materials team','Room B'],['11:15–12:00','Lunch','Courtyard'],['12:00–12:30','Questions','Auditorium']]})],[
 q('Where will the materials team meet?','Room B',['Room A','Courtyard','Auditorium'],'Bảng ghi Materials team lúc 10:00–11:15 ở Room B. Room A dành cho reception team, không phải nhóm materials.','table'),
 q('Why cannot volunteers attend both workshops?','They take place at the same time',['One workshop costs extra','Only one room has chairs','Lunch starts before the workshops'],'Hai workshop bắt đầu lúc 10 và kết thúc 11:15; phần hướng dẫn xác nhận diễn ra đồng thời. Không có thông tin phụ phí.','table-inference',[pair('both start at 10 A.M.','take place at the same time','hai buổi trùng thời gian')]),
 q('Who may skip the introductory briefing?','Returning volunteers',['All new volunteers','The materials team only','Anyone arriving after lunch'],'Returning volunteers là ngoại lệ được nêu; all new volunteers must attend nên người mới không được bỏ phần giới thiệu.','exception')
 ]);
 const freight=9+i,total=unit*quantity+freight;
 add('receipt',[doc('Briar Supplies — dispatch invoice',para(
 `Customer: ${t.org}\nContact: ${t.person}\nInvoice date: ${month} ${date}\nInvoice number: BR-${2400+i}`,
 `Your order has been packed for dispatch to ${t.venue}. A set of printed care instructions is enclosed at no charge. The freight amount shown below covers delivery to the reception counter; unpacking and installation are not included.`,
 `Payment is due within ten days of the invoice date. Please include the invoice number with your bank transfer. If the quantity delivered differs from the quantity shown here, email a photograph of the parcel label within three days of receipt. Do not send the products back until our support team gives you a return reference.`),{headers:['Item','Quantity','Unit price','Amount'],rows:[[t.item,String(quantity),`$${unit}`,`$${unit*quantity}`],['Care instructions','1 set','Included','$0'],['Freight','—','—',`$${freight}`],['Total','—','—',`$${total}`]]})],[
 q('What is supplied free of charge?','Care instructions',['Freight','Installation','A second set of products'],'Care instructions có Amount $0 và văn bản nói at no charge. Freight có phí; installation không được bao gồm.','table',[pair('at no charge','free of charge','miễn phí')]),
 q('How much is payable in total?',`$${total}`,[`$${unit*quantity}`,`$${total+unit}`,`$${total+freight}`],`${quantity} × $${unit} = $${unit*quantity}, cộng phí giao $${freight} được $${total}. Không cộng lại phí freight lần thứ hai.`, 'calculation'),
 q('What should a customer do if too few items arrive?','Email a photograph of the parcel label',['Return everything immediately','Wait ten days before reporting it','Request installation at reception'],'Quantity khác hóa đơn thì email ảnh label trong ba ngày. Bài yêu cầu không gửi trả trước khi có return reference.','procedure')
 ]);
 const [guideWord,guideMeaning]=[['clear','understandable'],['detailed','thorough'],['concise','brief'],['practical','useful'],['current','up-to-date'],['comprehensive','complete'],['straightforward','uncomplicated'],['handy','convenient'],['accurate','correct'],['helpful','useful']][i];
 add('review',[doc(`Customer review: ${t.org}`,para(
 `Posted by Robin Vale\nFour stars out of five`,
 `Our team attended the ${t.topic} introduction last month. I chose this provider because the program included supervised practice rather than lectures alone. The instructor explained each step clearly and let us repeat difficult tasks until we felt comfortable. The printed guide has proved ${guideWord} when we repeat the tasks back at our office.`,
 `There were twelve people in our group, which allowed everyone to ask questions. I particularly appreciated the short discussion of mistakes that beginners often make. We were not expected to buy supplies from the provider, and the instructor explained how to select suitable alternatives.`,
 `My only concern was the route to ${t.venue}. The confirmation email gave the street address but did not mention that the side entrance was closer to the bus stop. Better directions would have saved us a long walk. I would recommend the program, especially if that information is added to future messages.`))],[
 q('Why did the reviewer select the program?','It included supervised practice',['It sold the cheapest supplies','It guaranteed a professional license','It was available only online'],'Tác giả chọn vì supervised practice thay vì chỉ lectures; bài không nêu giá thấp nhất hoặc cấp bằng nghề.','reason'),
 q(`The word “${guideWord}” is closest in meaning to`,guideMeaning,['expensive','temporary','compulsory'],`Người viết mô tả printed guide là ${guideWord} khi dùng lại tại văn phòng. Trong ngữ cảnh chất lượng tài liệu, từ này tương đương ${guideMeaning}; không diễn tả giá, tính tạm thời hay bắt buộc.`, 'synonym',[pair(guideWord,guideMeaning,'đặc điểm của tài liệu hướng dẫn trong ngữ cảnh')]),
 q('What improvement is suggested?','Providing clearer arrival directions',['Removing practice activities','Increasing group size','Requiring supply purchases'],'Tác giả muốn email nêu side entrance gần bus stop; better directions tránh đi vòng, không phải thay nội dung lớp học.','detail',[pair('better directions','clearer arrival information','hướng dẫn đường đi rõ hơn')]),
 q('What is implied about the reviewer?','They would recommend the program',['They requested a full refund','They work as the instructor','They never attended the session'],'Câu cuối I would recommend the program cho thấy sẵn sàng giới thiệu, dù phàn nàn hướng dẫn đi lại. Không có yêu cầu hoàn tiền.','inference')
 ]);
 add('instructions',[doc('Requesting a group visit',para(
 `Groups wishing to visit ${t.org} should use the online request form. Enter the preferred date, the expected number of visitors, and the name of a group leader. A message acknowledging receipt will be sent automatically. This message does not reserve a date.`,
 `A coordinator will check the schedule and send an offer containing an available time and the applicable fee. The group leader must reply within two working days to accept the offer. If no reply is received, the offered time may be allocated to another group. Payment instructions will be sent after acceptance.`,
 `Groups may change their visitor count without charge until seven days before the visit. After that deadline, the fee will be based on the accepted count even if fewer people attend. Requests to add visitors are subject to space availability and must always be approved in advance.`))],[
 q('What does the automatic message indicate?','The request has reached the organization',['A date has been reserved','The fee has been paid','Additional visitors are approved'],'Acknowledging receipt chỉ xác nhận đã nhận form; văn bản nói rõ does not reserve a date nên chưa có đặt chỗ.','detail'),
 q('What must a group leader do to accept an offer?','Reply within two working days',['Send another automatic message','Visit seven days earlier','Pay before receiving an offer'],'Group leader phải reply within two working days; payment instructions chỉ gửi sau acceptance, không phải trước offer.','sequence'),
 q('What happens if fewer people attend after the count deadline?','The fee remains based on the accepted count',['The entire fee is refunded','The visit is automatically canceled','The group receives extra time'],'Sau deadline, phí dựa accepted count even if fewer attend. Không có giảm giá hay hủy chuyến tự động trong trường hợp này.','condition')
 ]);
 add('job advertisement',[doc(`${t.org} — ${t.job}`,para(
 `We are recruiting a ${t.job} for our ${t.city} office. The position involves answering routine inquiries, keeping appointment records, and coordinating with colleagues at ${t.venue}. [1]`,
 `Candidates must have at least six months of experience serving customers. Familiarity with scheduling software is desirable but is not essential, as training is provided. [2] The position includes one Saturday shift each month.`,
 `Applications should include a short cover letter and a current résumé. Send both documents to our recruitment address by ${month} ${date+5}. [3] Shortlisted applicants will be invited to a practical exercise followed by an interview.`,
 `The successful candidate is expected to start in the following month. Questions about the working schedule may be directed to ${t.person}; requests for an interview before the application deadline cannot be accommodated. [4]`))],[
 q('What is required of applicants?','Customer service experience',['A scheduling software certificate','Five years as a manager','Availability every Saturday'],'At least six months serving customers là bắt buộc. Software chỉ desirable và có đào tạo; lịch Saturday là một lần mỗi tháng.','qualification'),
 q('What will shortlisted candidates do?','Complete an exercise and attend an interview',['Start work without an interview','Buy their own software','Submit a second application fee'],'Practical exercise followed by an interview là bước kế tiếp cho shortlisted applicants; không có phí nộp hồ sơ.','sequence'),
 q('In which position does the following sentence best belong? “Applicants who have not used our system will therefore receive instruction during their first week.”','[2]',['[1]','[3]','[4]'],'Therefore và our system nối với scheduling software và training ngay trước [2]. Các vị trí khác nói nhiệm vụ, nộp hồ sơ hoặc ngày bắt đầu, không giới thiệu hệ thống.','sentence-insertion')
 ]);
 // Two double-document sets: 5 questions each.
 const discounted=fee-8;
 add('advertisement and e-mail',[doc(`${t.event}: early registration`,para(
 `${t.event} will take place at ${t.venue} on ${month} ${date+8}. The standard admission price is $${fee}. Registrations paid by ${month} ${date+1} receive an $8 reduction. The price includes all demonstrations but does not cover lunch or travel.`,
 `Organizations registering four or more participants may request a reserved row of seats. To do so, give the group name on the payment form. Individual tickets remain valid if another person attends in place of the original holder. Name changes must be reported to the event office no later than the day before the event. Printed tickets are not required; show the confirmation email at reception.`)),doc('E-mail: confirmation inquiry',para(
 `To: Event Office\nFrom: ${t.person}\nDate: ${month} ${date}\nSubject: Our group booking`,
 `I have just paid for five colleagues from ${t.org}, including myself. The confirmation email arrived, but it does not mention reserved seating. Could you check that our organization name appears on the booking? One colleague may be replaced by a new team member. I will confirm that person's name next week. We will bring our own lunches and travel together by train.`))],[
 q('What is included in admission?','All demonstrations',['Train travel','Lunch','An overnight room'],'Thông báo nói price includes all demonstrations và loại trừ lunch/travel, nên chỉ nội dung demonstration được gồm trong vé.','detail'),
 q('How much should each person in the group pay?',`$${discounted}`,[`$${fee}`,`$${fee+8}`,`$${fee-4}`],`Email ngày ${month} ${date} đã thanh toán, trước hạn ${date+1}. Đối chiếu quảng cáo giảm $8: $${fee} − $8 = $${discounted}/người.`, 'cross-document'),
 q('Why is the sender contacting the office?','To check the group seating arrangement',['To request travel reimbursement','To cancel the entire booking','To ask for free lunches'],'Email chưa ghi reserved seating; nhóm năm người đủ điều kiện tối thiểu bốn người trong thông báo, nên cần kiểm tra tên tổ chức.','cross-document'),
 q('What may the sender do regarding a colleague?','Transfer a ticket to another person',['Use two tickets for the same seat','Demand a refund after the event','Attend without any confirmation'],'Thông báo cho phép another person dùng vé nếu báo tên; email nói một colleague có thể được thay bằng new team member.','cross-document',[pair('another person attends in place of the original holder','transfer a ticket','chuyển vé cho người thay thế')]),
 q('What should attendees present at reception?','The confirmation email',['A printed train timetable','A lunch receipt','A staff employment contract'],'Quảng cáo nói show confirmation email, không bắt buộc printed tickets. Email cũng xác nhận đã nhận thư này.','detail')
 ]);
 add('course listing and e-mail',[doc(`${t.org}: course options`,para(
 `All courses below introduce practical techniques in ${t.topic}. Fees include the workbook and supervised exercises. Participants must attend the whole session to receive an attendance certificate. The online course requires a stable internet connection; recordings are not supplied.`,
 `The morning and evening classroom courses cover the same material. The weekend course includes an additional project discussion. Applications close three days before each course begins. Choose the course code on the registration form. Changes to another session may be requested while places remain available, but participants must pay any difference in price.`),{headers:['Code','Format','Time','Fee'],rows:[['M1','Classroom','9 A.M.–12 P.M.','$60'],['E2','Classroom','6 P.M.–9 P.M.','$60'],['O3','Online','2 P.M.–5 P.M.','$45'],['W4','Classroom','Saturday 9 A.M.–1 P.M.','$80']]}),doc('E-mail: choosing a session',para(
 `From: ${t.person}\nTo: Training Office\nSubject: Course selection`,
 `I work every weekday until 5 P.M. and have a family commitment this Saturday. I would prefer to attend in person rather than online. Please reserve a place for me in the session that fits these conditions. My colleague, Riley, has registered for the online session but now wants to join me. Please tell Riley how much extra needs to be paid if a place is available. We will bring our confirmation messages on arrival.`))],[
 q('Which course suits the sender?','E2',['M1','O3','W4'],'Email yêu cầu sau 5 giờ ngày thường, trực tiếp, không Saturday; bảng chỉ E2 classroom 6–9 P.M. đáp ứng cả ba điều kiện.','cross-document'),
 q('How much more must Riley pay to join the sender?','$15',['$20','$35','$60'],'Online O3 $45 đổi sang E2 $60, chênh $15. Chính sách yêu cầu trả phần chênh nếu còn chỗ, không thanh toán lại toàn bộ.','cross-document-calculation'),
 q('What is included in every fee?','A workbook',['A course recording','A family ticket','A professional license'],'Listing ghi Fees include workbook and supervised exercises. Online không có recordings; certificate chỉ là attendance.','detail'),
 q('What is required for an attendance certificate?','Completing the entire session',['Attending the online course only','Paying an additional fee','Submitting a separate project'],'Must attend the whole session là điều kiện nhận certificate cho mọi khóa, không giới hạn online hay Saturday.','condition'),
 q('What is implied about Riley?','Riley originally selected a different format',['Riley has already finished the course','Riley cannot use the internet','Riley will attend the Saturday course'],'Riley đăng ký online nhưng muốn join sender ở classroom; đây là thay đổi hình thức, không phải đã học xong hay chọn weekend.','cross-document-inference')
 ]);
 // Three triple-document sets: calculations, policy exceptions, and links between sources.
 const room=80+i*5,deposit=25,balance=room-deposit;
 add('room listing, reservation, and e-mail',[doc(`${t.venue}: room hire`,para(
 `Meeting rooms can be hired for half-day sessions. The Cedar room seats twelve and costs $${room}; the Elm room seats twenty and costs $${room+30}. Both rooms include a screen and drinking water. Refreshments can be added for $4 per person if requested at least two days in advance.`,
 `A $25 deposit is required when a booking is accepted. The balance is due on the day of use. Groups may change to a larger room if one is available, paying the difference in room price. Deposits cannot be refunded for cancellations made less than three days before the booking.`)),doc('Reservation record',`Group: ${t.org}\nContact: ${t.person}\nDate of use: ${month} ${date+6}\nRoom: Cedar\nExpected attendance: 10\nDeposit paid: $25\nRefreshments: Not requested`,{headers:['Room','Seats','Half-day price'],rows:[['Cedar','12',`$${room}`],['Elm','20',`$${room+30}`]]}),doc('E-mail: additional guests',para(
 `To: Venue Office\nFrom: ${t.person}\nDate: ${month} ${date+2}\nSubject: Room change`,
 `Four additional colleagues will attend our meeting, bringing the total to fourteen. Please move us to the larger room if it is still available. We would also like refreshments for everyone. Our original deposit has already been paid. Please confirm the amount remaining so I can arrange payment on arrival. The meeting date and half-day duration will stay the same.`))],[
 q('Which room was originally reserved?','Cedar',['Elm','The reception counter','The dining room'],'Reservation record ghi Room Cedar; Elm là phòng lớn mà email sau muốn đổi sang, không phải đặt ban đầu.','detail'),
 q('Why does the group need another room?','Its attendance exceeds the original room capacity',['Its meeting will last two days','The screen has been removed','The original room has closed'],'Email nói tổng 14; Cedar trong listing chỉ 12 chỗ. Cần đối chiếu hai tài liệu để thấy phòng ban đầu không đủ sức chứa.','cross-document'),
 q('How much remains payable if both requests are approved?',`$${room+30+14*4-deposit}`,[`$${balance}`,`$${room+30+14*4}`,`$${room+30-deposit}`],`Elm $${room+30} + refreshments 14 × $4 = $${room+30+56}; trừ deposit $25 đã trả còn $${room+30+56-25}. Không bỏ qua refreshment hay thu lại deposit.`, 'cross-document-calculation'),
 q('What is indicated about the refreshment request?','It was made before the stated deadline',['It was made on the day of use','It requires changing the meeting date','It is included in the room price'],'Email ngày '+`${date+2}, buổi họp ${date+6}: trước bốn ngày, đủ yêu cầu ít nhất hai ngày trong listing. Refreshments có phí riêng.`, 'cross-document'),
 q('What will remain unchanged?','The meeting date',['The room capacity','The number of attendees','The refreshment choice'],'Email nói meeting date và half-day duration stay same; số người, phòng và refreshments đều đang được yêu cầu thay đổi.','detail')
 ]);
 const refund=fee-5;
 add('membership policy, account record, and e-mail',[doc(`${t.org}: membership terms`,para(
 `A monthly membership costs $${fee} and includes access to the general sessions. Specialist workshops are booked separately and are not included. New members have seven days from activation to cancel for a refund, provided they have not attended any session. A $5 processing fee is deducted from eligible refunds.`,
 `Members who have already attended a session may cancel renewal for the following month, but the current month's payment is not refundable. To cancel, email the membership office with your account number. Requests received by telephone alone are not processed. Changes to a contact address can be made through the online account page.`)),doc('Account activity',`Name: ${t.person}\nAccount: AC-${2410+i}\nActivation date: ${month} ${date}\nMonthly payment: $${fee}\nGeneral session attendance: None\nSpecialist workshops: None`),doc('E-mail: cancellation request',para(
 `To: Membership Office\nFrom: ${t.person}\nDate: ${month} ${date+4}\nSubject: Account AC-${2410+i}`,
 `My work schedule has changed, and I can no longer attend the sessions I planned to join. I have not used the membership. Please cancel my account and refund the eligible amount to the card used for payment. I understand that a processing charge may apply. I hope to register again once my schedule is more predictable.`))],[
 q('What does the membership include?','General sessions',['All specialist workshops','Unlimited private training','Free travel to the venue'],'Policy chỉ includes general sessions; specialist workshops được đặt riêng. Không có thông tin private training hoặc travel.','detail'),
 q('Why is the member eligible for a refund?','The request is timely and no session has been attended',['All members receive full refunds at any time','A workshop was canceled by the provider','The activation payment was missing'],'Email sau activation bốn ngày, trong bảy ngày; account record ghi None ở attendance. Cả hai điều kiện refund đều thỏa mãn.','cross-document'),
 q('How much should be refunded?',`$${refund}`,[`$${fee}`,`$${fee+5}`,'$5'],`Account đã trả $${fee}; policy trừ processing fee $5 nên refund $${fee-5}. Không hoàn toàn bộ và cũng không chỉ hoàn khoản phí xử lý.`, 'cross-document-calculation'),
 q('Why is the member canceling?','A work schedule has changed',['The center raised all workshop prices','A card payment failed','The membership was activated twice'],'Email trực tiếp nói my work schedule has changed; không nêu lý do tăng phí hay lỗi thanh toán.','reason'),
 q('How must cancellations be requested?','By email with an account number',['By telephone alone','By returning a workbook','Through the address-change page'],'Policy yêu cầu email membership office kèm account number; email đã dùng subject số AC tương ứng. Telephone alone không được xử lý.','procedure')
 ]);
 add('supplier notice, order, and delivery message',[doc('Briar Supplies: dispatch update',para(
 `Orders for ${t.item} placed before noon are usually dispatched on the next working day. During this month's stock review, a temporary delay of two working days applies to orders containing more than ten sets. Smaller orders follow the normal schedule. Customers will receive tracking details when the parcel leaves our premises.`,
 `Items are packed in cartons containing up to five sets each. The cartons are numbered so receiving teams can identify a missing parcel. Shipping is charged once per order, regardless of the number of cartons. Customers should inspect the carton seals before signing for delivery. A broken seal should be recorded on the driver's delivery form.`)),doc('Purchase order',`Customer: ${t.org}\nContact: ${t.person}\nOrder reference: PO-${2480+i}\nProduct: ${t.item}\nQuantity: 13 sets\nTime submitted: Monday, 10 A.M.\nDeliver to: ${t.venue}`),doc('Message from the supplier',para(
 `To: ${t.person}\nSubject: Order PO-${2480+i}`,
 `We have accepted your order. All thirteen sets are available, but the temporary stock-review timetable applies to this quantity. We expect dispatch on Thursday. Your goods will be divided among three numbered cartons. The tracking message will list each carton separately, although you will still pay only one shipping charge. If any carton is missing on arrival, tell us its number before sending an enquiry about individual products.`))],[
 q('Why is this order affected by a delay?','It contains more than ten sets',['It was placed after noon','The products are out of stock','The address is outside the delivery area'],'Order 13 sets >10 nên áp dụng delay trong notice. Đặt Monday 10 A.M. trước noon và message xác nhận đủ hàng, loại hai bẫy này.','cross-document'),
 q('When does the supplier expect to dispatch the order?','Thursday',['Monday','Tuesday','Friday'],'Supplier message trực tiếp xác nhận Thursday; lịch thường là next working day nhưng đơn này chịu thêm hai working days.','detail'),
 q('How many cartons should arrive?','Three',['Two','Five','Thirteen'],'Mỗi carton tối đa 5 sets; 13 cần 3 cartons. Delivery message cũng xác nhận three numbered cartons nên có hai căn cứ.','cross-document-calculation'),
 q('What should the receiver do if a carton seal is broken?','Record it on the delivery form',['Pay a second shipping charge','Discard all tracking details','Wait until the next stock review'],'Notice yêu cầu broken seal recorded on driver delivery form trước khi ký; không nói phải trả phí thêm hoặc chờ kiểm kê.','procedure'),
 q('What is suggested about the shipping charge?','It does not increase with the number of cartons',['It is collected separately for each set','It has been waived entirely','It includes a monthly membership'],'Notice ghi once per order regardless cartons; supplier message cũng nói only one charge cho ba kiện. Không được hiểu là miễn phí.','cross-document-inference',[pair('regardless of the number of cartons','one shipping charge per order','phí theo đơn, không theo số kiện')])
 ]);
 return groups;
}
